---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-deployment
  labels:
    app: js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      labels:
        app: js
    spec:
      containers:
      - name: js-app
        image: alexolink/js-prob:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: js-service
spec:
  type: NodePort
  selector:
    app: js
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007